package com.mcloud.matrix.outstock.mybatis.mapper;

import com.mcloud.matrix.outstock.mybatis.entity.TOutstockSku;
import com.mcloud.matrix.outstock.mybatis.entity.TOutstockSkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOutstockSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_sku
     *
     * @mbg.generated
     */
    long countByExample(TOutstockSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_sku
     *
     * @mbg.generated
     */
    int deleteByExample(TOutstockSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_sku
     *
     * @mbg.generated
     */
    int insert(TOutstockSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_sku
     *
     * @mbg.generated
     */
    int insertSelective(TOutstockSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_sku
     *
     * @mbg.generated
     */
    List<TOutstockSku> selectByExample(TOutstockSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_sku
     *
     * @mbg.generated
     */
    TOutstockSku selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_sku
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TOutstockSku record, @Param("example") TOutstockSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_sku
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TOutstockSku record, @Param("example") TOutstockSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TOutstockSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TOutstockSku record);
}